16:13:16 WARNI| This marks test as WARN
16:13:16 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
16:13:16 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
16:13:16 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
16:13:16 ERROR| WARN 1-examples/warntest.py:WarnTest.test -> TestWarn: Test passed but there were warnings during execution. Check the log for details.
16:13:16 INFO | 
